'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.join(__dirname,'..');
const permissions=require(path.join(root,'js','permissions.js'));
const core=fs.readFileSync(path.join(root,'js','core.js'),'utf8');
const employees=fs.readFileSync(path.join(root,'js','employees.js'),'utf8');
const schools=fs.readFileSync(path.join(root,'js','schools.js'),'utf8');
const hireWaiting=fs.readFileSync(path.join(root,'js','hire-waiting-list.js'),'utf8');
const source=fs.readFileSync(path.join(root,'js','permissions.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.equal(permissions.VERSION,'12.0.2');
for(const role of ['admin','local_admin','legacy_admin'])assert(permissions.has('applicant.delete',role));
assert(permissions.has('applicant.write','recruiter'));
assert(permissions.has('schedule.write','recruiter'));
assert(permissions.has('audit.write','recruiter'));
assert(!permissions.has('applicant.delete','recruiter'));
assert(!permissions.has('employee.write','recruiter'));
assert(permissions.has('applicant.read','viewer'));
assert(permissions.has('stats.read','viewer'));
assert(!permissions.has('applicant.write','viewer'));
assert(!permissions.has('backup.restore','viewer'));
assert(!permissions.has('sensitive.read','viewer'));
assert(!permissions.has('audit.read','viewer'));
assert(permissions.has('readiness.manage','admin'));
assert(!permissions.has('readiness.manage','recruiter'));
assert(!permissions.has('readiness.manage','viewer'));
assert(permissions.has('storage.manage','local_admin'));

assert.match(core,/erpPermissions\.require\('applicant\.write'\)/);
assert.match(employees,/erpPermissions\.require\('employee\.write'/);
assert.match(employees,/erpPermissions\.require\('employee\.delete'/);
assert.match(schools,/erpPermissions\.require\('school\.write'/);
assert.match(schools,/erpPermissions\.require\('school\.delete'/);
assert.match(hireWaiting,/placeholder="관리자만 조회"/);
assert.match(hireWaiting,/erpPermissions\.require\('sensitive\.read'/);
assert.match(index,/js\/permissions\.js\?v=12\.0\.2/);
assert.match(index,/js\/audit-history\.js\?v=12\.0\.2/);
assert.match(index,/css\/permissions\.css\?v=12\.0\.2/);
assert.match(index,/css\/audit-history\.css\?v=12\.0\.2/);
assert.equal(permissions.requiredPermission({dataset:{page:'storagePerformance'}}),'storage.manage');
assert.equal(permissions.requiredPermission({dataset:{page:'productionReadiness'}}),'readiness.manage');
assert.equal(permissions.useLocal('', 'viewer').role,'viewer');
assert.equal(permissions.current().source,'local');
permissions.useLocal();
assert.equal(permissions.current().role,'local_admin');
assert.doesNotMatch(source,/supabase|root\.sb|fetch\(|getSession|signIn|signOut/i);
for(const retired of ['supabase_migration_v10.57.0_rbac_rls.sql','js/auth-init.js','js/cloud-sync.js'])assert.equal(fs.existsSync(path.join(root,retired)),false);
console.log('permissions.test.js: LOCAL ONLY 역할표·화면 보호·민감정보 마스킹·원격 권한 계층 제거 확인 완료');
