'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');

const index=read('index.html');
const applicants=read('js/applicants.js');
const enhancements=read('js/ui-enhancements.js');
const permissions=read('js/permissions.js');
const audit=read('js/audit-history.js');
const layout=read('css/layout.css');
const uiLayout=read('css/ui-layout.css');
const listLayout=read('css/list-layout.css');
const clearview=read('css/applicant-clearview.css');
const calm=read('css/design-calm-cascade.css');
const readiness=read('css/production-readiness.css');
const hireWaitingList=read('js/hire-waiting-list.js');
const hireWaitingCss=read('css/hire-waiting-list.css');
const dailyOperationsCss=read('css/daily-operations-polish.css');
const applicantWorksheet=read('js/applicant-worksheet.js');
const applicantWorksheetCss=read('css/applicant-worksheet.css');
const densityCss=read('css/ui-density-navigation.css');
const quickDetailCss=read('css/applicant-quick-detail.css');

const queue=index.match(/<div class="home-work-queue"[^>]*>([\s\S]*?)<\/div>/)?.[1]||'';
const queueTargets=[...queue.matchAll(/class="queue-card[^\"]*" data-task-target="([^"]+)"/g)].map(match=>match[1]);
assert.deepEqual(queueTargets,['today','overdue','contact','decision','hire'],'홈 업무 카드가 정확히 5개여야 합니다.');
const kpiBlock=enhancements.match(/const kpis=\[([\s\S]*?)\];/)?.[1]||'';
const kpiKeys=[...kpiBlock.matchAll(/\['[^']+',\s*[^,]+,\s*'([^']+)'/g)].map(match=>match[1]);
assert.deepEqual(kpiKeys,['applicants','active','monthApplications','hirePlanned'],'홈 누적 KPI가 정확히 4개여야 합니다.');
assert.equal(kpiKeys.some(key=>queueTargets.includes(key)),false,'누적 KPI와 오늘 업무 키가 중복되면 안 됩니다.');
assert.doesNotMatch(uiLayout,/queue-card[^\n{}]*nth-child[^{}]*display\s*:\s*none/i);
assert.match(enhancements,/today:'interviewToday',overdue:'overdue',contact:'contact',decision:'resultPending',hire:'hireUpcoming'/);
assert.match(enhancements,/function uxConsolidateSidebarStatus\(\)/);assert.match(enhancements,/dataset\.sidebarStatusArea/);assert.match(enhancements,/authUserMark/);
assert.match(densityCss,/--erp-sidebar-w:224px/);assert.match(densityCss,/\.nav-btn,.nav-btn\.nav-sub\{height:36px!important;min-height:36px!important/);assert.match(densityCss,/height:44px!important;min-height:44px!important/);
assert.match(densityCss,/grid-template-columns:minmax\(0,1fr\) auto/);assert.match(densityCss,/max-height:calc\(100vh - 292px\)/);assert.match(densityCss,/\.applicant-list-empty-state/);assert.doesNotMatch(densityCss,/localStorage|sessionStorage|Supabase|shared-storage/);
['searchInput','sortSelect','hideFinished','btnOpenApplicantFilter','bulkModeButton','btnResetFilters'].forEach(id=>assert.match(index,new RegExp(`id="${id}"`)));
const accessibleNames={searchInput:'지원자 검색',sortSelect:'지원자 정렬',calendarWorkplaceFilter:'일정 근무지 필터',dailyWorkflowSearch:'오늘 할 일 검색',rosterDate:'면접 명단 날짜'};
Object.entries(accessibleNames).forEach(([id,label])=>assert.match(index,new RegExp(`aria-label="${label}"[^>]*id="${id}"|id="${id}"[^>]*aria-label="${label}"`),`${id} 접근 가능한 이름이 없습니다.`));
assert.deepEqual([...index.matchAll(/data-filter="([^"]+)"/g)].map(match=>match[1]).slice(0,9),['all','active','docpass','interview','hire','finished','contact','decision','duplicate']);
assert.deepEqual([...index.matchAll(/data-workplace="([^"]+)"/g)].map(match=>match[1]).slice(0,4),['all','천안','평택','기타']);
assert.match(applicants,/applicant-list-empty-state/);assert.match(applicants,/applicant-empty-register/);assert.match(applicants,/applicant-empty-reset/);assert.match(applicants,/erpPermissions\.has\('applicant\.write'\)/);

['no-head','name-head','workplace-head','status-head','actions-head'].forEach(className=>assert.match(index,new RegExp(`class="${className}"`)));
['sticky-app-no','sticky-app-name','sticky-app-workplace','sticky-app-status','sticky-app-actions'].forEach(className=>assert.match(applicants,new RegExp(className)));
assert.doesNotMatch(listLayout,/applicant-table[^\n{]*nth-child/,'지원자 열 소유권은 applicant-clearview.css에만 있어야 합니다.');
assert.doesNotMatch(clearview,/applicant-table\s+(?:thead\s+)?th:nth-child/,'지원자 고정 열은 의미 클래스를 사용해야 합니다.');
assert.doesNotMatch(calm,/applicant-table\s+thead\s+th:nth-child/,'최종 디자인도 지원자 열 번호에 의존하면 안 됩니다.');
assert.match(clearview,/\.workplace-head[\s\S]*\.workplace-cell/);assert.match(clearview,/\.actions-head[\s\S]*\.applicant-actions[\s\S]*right:0/);

const statusWorkflow=enhancements.match(/\/\* ---------- Status workflow ---------- \*\/[\s\S]*?\/\* ---------- Shared task cards ---------- \*\//)?.[0]||'';
assert.match(statusWorkflow,/applicantStatusModal/);assert.match(statusWorkflow,/aria-modal/);assert.match(statusWorkflow,/event\.key==='Escape'/);assert.match(statusWorkflow,/event\.key==='Tab'/);assert.doesNotMatch(statusWorkflow,/\bprompt\s*\(/);
assert.match(statusWorkflow,/uxAppendStatusMemo/);assert.match(statusWorkflow,/메모 추가/);assert.match(statusWorkflow,/if\(newMemo\)patch\.memo/);assert.match(statusWorkflow,/applicants=previous;renderAll\(\)/);
assert.match(enhancements,/required:\['name','phone','applyDate','workplace'\]/);assert.match(enhancements,/step-needs-review/);assert.match(enhancements,/optional:true/);assert.match(enhancements,/선택 입력/);assert.match(enhancements,/필수 \$\{requiredComplete\}\/\$\{requiredTotal\} 단계 완료/);
assert.doesNotMatch(calm,/^\.page-intro-card\{display:flex!important;\}/m);assert.match(calm,/\.page-intro-card\.safety-intro-card\{display:flex!important;\}/);assert.match(uiLayout,/#home \.home-dashboard-intro,#stats \.stats-intro\{display:none!important;\}/);

assert.match(permissions,/permission-matrix-row/);assert.match(permissions,/마지막 관리자 계정/);assert.match(permissions,/permission-result-notice/);
assert.match(audit,/auditTypeFilter/);assert.match(audit,/auditActionFilter/);assert.match(audit,/AUDIT_PAGE_SIZE=20/);assert.match(audit,/audit-detail/);
assert.match(layout,/html\{background:#f5f6f8;overflow-x:hidden;\}/);assert.match(layout,/body\{background:#f5f6f8;overflow-x:hidden;\}/);
assert.match(calm,/focus-visible/);assert.match(calm,/min-height:44px/);
assert.match(applicants,/document\.body\.dataset\.activePage=page/);
assert.match(uiLayout,/body\[data-active-page="form"\] \.topbar/);
const visualTest=read('tests/ui-visual-layout.js');
assert.match(visualTest,/formWorkflowBanner/);assert.match(visualTest,/formActions\.overlaps,false/);
assert.match(visualTest,/390x844-status-modal\.png'\),fullPage:false/);
assert.match(visualTest,/390x844-sync-conflict\.png'\),fullPage:false/);
assert.match(index,/css\/applicant-worksheet\.css\?v=11\.4\.1/);assert.match(index,/js\/applicant-worksheet\.js\?v=11\.4\.1/);assert.match(index,/css\/ui-density-navigation\.css\?v=11\.4\.1/);
assert.match(applicantWorksheet,/일반보기/);assert.match(applicantWorksheet,/워크시트 보기/);assert.match(applicantWorksheet,/변경 \$\{entries\.length\}건/);
assert.match(applicantWorksheet,/root\.save\(\)/);assert.match(applicantWorksheet,/applicants=snapshot/);assert.match(applicantWorksheet,/beforeunload/);
assert.match(applicantWorksheetCss,/nth-child\(2\).*position:sticky/);assert.match(applicantWorksheetCss,/nth-child\(3\).*position:sticky/);assert.match(applicantWorksheetCss,/--worksheet-phone-left/);assert.match(applicantWorksheet,/syncStickyOffsets/);assert.match(applicantWorksheet,/getBoundingClientRect\(\)\.width/);assert.match(applicantWorksheetCss,/\.worksheet-cell\.is-dirty/);assert.match(applicantWorksheetCss,/\.worksheet-cell\.is-error/);
assert.match(densityCss,/overflow:visible!important;[\s\S]*flex-wrap:wrap!important/);assert.match(densityCss,/#applicants #quickFilters \.chip\{[^}]*height:36px!important;min-height:36px!important/);assert.match(densityCss,/#calendar \.calendar-today-dot\{[^}]*color:#fff!important/);assert.match(densityCss,/\.sidebar \.nav\{[^}]*overflow-y:auto/);
assert.match(visualTest,/1440x900/);assert.match(visualTest,/verifyApplicantWorksheet/);assert.match(visualTest,/__worksheetSaveCalls/);
assert.match(visualTest,/const denseApplicants=Array\.from\(\{length:60\}/);assert.match(visualTest,/visibleRows>=3/);assert.match(visualTest,/390x844-mobile-menu\.png/);assert.match(visualTest,/\$\{label\}-sidebar\.png/);
assert.match(index,/css\/applicant-quick-detail\.css\?v=11\.4\.1/);assert.match(applicants,/openApplicantQuickDetail/);assert.match(applicants,/moveApplicantQuickDetail/);assert.match(applicants,/행 클릭 → 빠른 보기/);
assert.match(applicants,/window\.viewApplicant\?\.\(id\)/);assert.match(applicants,/window\.editApplicant\?\.\(id\)/);assert.match(applicants,/applicantQuickDetailCanWrite/);assert.doesNotMatch(applicants.match(/function renderApplicantQuickDetail\(\)[\s\S]*?function openApplicantQuickDetail\(/)?.[0]||'',/residentNumber|Object\.values/);
assert.match(quickDetailCss,/width:clamp\(420px,34vw,480px\)/);assert.match(quickDetailCss,/@media\(max-width:900px\)[\s\S]*width:100%/);assert.match(visualTest,/verifyApplicantQuickDetail/);assert.match(visualTest,/bridgeSaveRequests,0/);assert.match(visualTest,/applicant-quick-detail-long-memo\.png/);

const emptyTopbarButtons=[...index.matchAll(/<button[^>]*class="[^"]*topbar-icon-btn[^"]*"[^>]*>[\s\S]*?<\/button>/g)];
assert.equal(emptyTopbarButtons.length,0,'기능 없는 상단 아이콘 버튼이 남아 있습니다.');
assert.match(read('css/privacy-security.css'),/\.privacy-shield-button\{display:inline-grid!important/);
assert.match(readiness,/readiness-check-grid/);assert.match(readiness,/@media\(max-width:600px\)/);
assert.match(visualTest,/\$\{viewport\.name\}-production-readiness\.png/);assert.match(visualTest,/1366x768-zoom125-production-readiness\.png/);
assert.match(visualTest,/412x915/);assert.match(visualTest,/1363x936-sidebar/);assert.match(visualTest,/verifyUsabilityPolish/);assert.match(visualTest,/sticky\.phone\.left-sticky\.name\.right/);assert.match(visualTest,/quickOverflow<=1/);assert.match(visualTest,/ariaCurrent==='date'/);

const hireWaitingKeys=['no','employeeNo','contactStatus','hireDate','workplace','pmtc','gender','groupName','product','part','name','rank','residentNumber','birthDate','age','email','education','school','major','phone','region','commuteMethod','remarks'];
const declaredHireWaitingKeys=[...hireWaitingList.matchAll(/\{key:'([^']+)',label:/g)].map(match=>match[1]);
assert.deepEqual(declaredHireWaitingKeys,hireWaitingKeys,'입사대기 회사 양식 23열 순서가 유지되어야 합니다.');
assert.match(hireWaitingList,/ensureHireWaitingColumnSemantics/);assert.match(hireWaitingList,/th\.dataset\.colKey=column\.key/);assert.match(hireWaitingList,/hireWaitingColumnClass\(col\.key\)/);
assert.doesNotMatch(hireWaitingCss,/\.hire-waiting-table[^{}]*(?:first-child|nth-child)/,'입사대기 핵심 열 스타일은 열 번호가 아니라 data-col-key를 사용해야 합니다.');
assert.doesNotMatch(dailyOperationsCss,/\.hire-waiting-table[^{}]*(?:first-child|nth-child)/,'후순위 디자인 CSS가 입사대기 열 번호를 다시 덮어쓰면 안 됩니다.');
const hireWaitingWidths={no:52,employeeNo:124,contactStatus:88,hireDate:104,workplace:90,pmtc:108,gender:64,groupName:112,product:112,part:112,name:118,rank:88,residentNumber:150,birthDate:112,age:60,email:230,education:100,school:210,major:210,phone:136,region:120,commuteMethod:108,remarks:420};
Object.entries(hireWaitingWidths).forEach(([key,width])=>assert.match(hireWaitingCss,new RegExp(`\\[data-col-key="${key}"\\]\\{width:${width}px;min-width:${width}px`),`${key} 열 너비가 업무 기준과 달라졌습니다.`));
assert.match(hireWaitingCss,/data-col-key="employeeNo"\]\{position:sticky;left:var\(--hire-waiting-no-width\)/);assert.match(hireWaitingCss,/data-col-key="name"\]\{position:sticky;left:calc\(var\(--hire-waiting-no-width\) \+ var\(--hire-waiting-employee-width\)\)/);
['name','email','school','major','phone','region'].forEach(key=>assert.match(hireWaitingCss,new RegExp(`data-col-key="${key}"`)));
assert.match(hireWaitingCss,/text-overflow:clip/);assert.match(hireWaitingCss,/tbody tr:focus-within td/);assert.match(hireWaitingCss,/td:focus-within/);
assert.match(hireWaitingList,/HIRE_WAITING_AUTO_HIGHLIGHT_MS=4000/);assert.match(hireWaitingList,/td\.is-auto-filled/);assert.doesNotMatch(hireWaitingList,/localStorage\.setItem\([^\n]*highlight/i,'자동입력 강조 상태를 저장하면 안 됩니다.');

console.log('ui-layout.test.js: 5개 업무 카드·입사대기 23열·고정 열·모바일 권한/감사·상태 팝업 확인 완료');
