begin;

create schema if not exists private;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  client_event_id uuid not null unique,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_label text not null default '알 수 없음',
  actor_role text not null check (actor_role in ('admin','recruiter')),
  entity_type text not null,
  entity_id text not null default '',
  entity_label text not null default '기록',
  action text not null check (action in ('create','update','delete','restore','export','role_change','batch')),
  changed_fields text[] not null default '{}',
  before_values jsonb not null default '{}'::jsonb,
  after_values jsonb not null default '{}'::jsonb,
  reason text not null default '',
  source text not null default 'cloud',
  app_version text not null default '10.58.0',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_occurred_id_idx on public.audit_logs (occurred_at desc,id desc);
create index if not exists audit_logs_entity_occurred_idx on public.audit_logs (entity_type,occurred_at desc,id desc);
create index if not exists audit_logs_actor_occurred_idx on public.audit_logs (actor_user_id,occurred_at desc,id desc);

alter table public.audit_logs enable row level security;
revoke all on table public.audit_logs from public, anon, authenticated;
grant select, insert on table public.audit_logs to authenticated;
revoke all on sequence public.audit_logs_id_seq from public, anon;
grant usage, select on sequence public.audit_logs_id_seq to authenticated;

create or replace function private.erp_audit_scrub_json(payload jsonb)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select coalesce(jsonb_object_agg(key,
    case
      when key ~* '(name|phone|mobile|email|address|resident|rrn|ssn|birth|password|secret|token|bank|account|salary|memo|note|reason|consult|content|title|description|history)'
        then to_jsonb('개인정보/내용 변경됨'::text)
      when jsonb_typeof(value) in ('object','array') then to_jsonb('복합정보 변경됨'::text)
      when jsonb_typeof(value)='string' then to_jsonb(
        regexp_replace(regexp_replace(regexp_replace(value #>> '{}','[0-9]{6}[ -]?[1-4][0-9]{6}','[주민등록번호 숨김]','g'),'01[016789][ .-]?[0-9]{3,4}[ .-]?[0-9]{4}','[전화번호 숨김]','g'),'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}','[이메일 숨김]','g')
      )
      else value
    end
  ), '{}'::jsonb)
  from jsonb_each(coalesce(payload,'{}'::jsonb));
$$;

revoke all on function private.erp_audit_scrub_json(jsonb) from public, anon, authenticated;

create or replace function private.erp_prepare_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_role text;
  current_email text;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select ur.role,ur.email into current_role,current_email from public.user_roles ur where ur.user_id=auth.uid();
  if current_role not in ('admin','recruiter') then raise exception 'audit write permission denied'; end if;
  new.actor_user_id:=auth.uid();
  new.actor_role:=current_role;
  new.actor_label:=case when position('@' in coalesce(current_email,''))>1 then left(current_email,1)||'***@'||split_part(current_email,'@',2) else '로그인 사용자' end;
  new.before_values:=private.erp_audit_scrub_json(new.before_values);
  new.after_values:=private.erp_audit_scrub_json(new.after_values);
  new.metadata:=private.erp_audit_scrub_json(new.metadata);
  new.entity_label:=case when new.entity_type in ('applicant','employee','schedule','user') then left(coalesce(new.entity_label,'기록'),1)||'***' else left(coalesce(new.entity_label,'기록'),80) end;
  new.reason:=left(regexp_replace(regexp_replace(regexp_replace(coalesce(new.reason,''),'[0-9]{6}[ -]?[1-4][0-9]{6}','[주민등록번호 숨김]','g'),'01[016789][ .-]?[0-9]{3,4}[ .-]?[0-9]{4}','[전화번호 숨김]','g'),'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}','[이메일 숨김]','g'),300);
  new.source:='cloud';new.created_at:=now();
  return new;
end;
$$;

revoke all on function private.erp_prepare_audit_log() from public, anon, authenticated;
drop trigger if exists erp_prepare_audit_log on public.audit_logs;
create trigger erp_prepare_audit_log before insert on public.audit_logs for each row execute function private.erp_prepare_audit_log();

drop policy if exists erp_audit_logs_admin_read on public.audit_logs;
drop policy if exists erp_audit_logs_actor_insert on public.audit_logs;
create policy erp_audit_logs_admin_read on public.audit_logs for select to authenticated using ((select private.erp_current_role())='admin');
create policy erp_audit_logs_actor_insert on public.audit_logs for insert to authenticated with check ((select private.erp_current_role()) in ('admin','recruiter') and actor_user_id=(select auth.uid()));

commit;

select schemaname,tablename,rowsecurity from pg_tables where schemaname='public' and tablename='audit_logs';
select policyname,cmd,roles from pg_policies where schemaname='public' and tablename='audit_logs' order by policyname;
